name: happy_wave
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.14.0
  firebase_auth: ^5.5.3
  cloud_firestore: ^5.6.7
  image_picker: ^1.1.2
  firebase_storage: ^12.4.5
  permission_handler: ^12.0.0+1
  flutter_chat_types: ^3.6.2
  intl: ^0.20.2
  firebase_vertexai: ^1.6.0
  firebase_ai: ^2.0.0
  flutter_launcher_icons: ^0.14.3
  firebase_messaging: ^15.2.7
  url_launcher: ^6.3.1
  # 데이터직렬화
  json_annotation: ^4.9.0
  # 상태관리
  flutter_riverpod: ^2.6.1
  # 암호화
  crypto: ^3.0.6
  encrypt: ^5.0.3
  bcrypt: ^1.1.3
  # 알림 기능
  flutter_local_notifications: ^19.3.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  # 데이터직렬화
  json_serializable: ^6.9.4
  build_runner: ^2.4.15 # dart run build_runner build

flutter:
  uses-material-design: true

  assets:
    - assets/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21